#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname factorial -mnesia debug verbose

main([Root]) ->
  try
    io:format("Device: ~p~n", [mounts:get_mount(Root)]),
    io:format("~p~n", [devices:block_device_id(Root)]),
    crawl:print(Root)
  catch
    ErrorType:Error ->
      io:format("Error: ~s ~s~n", [ErrorType, Error])
    end;
main(_) ->
  usage().

usage() ->
  io:format("usage: crawl path\n"),
    halt(1).
