#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname factorial -mnesia debug verbose

main([Root]) ->
  try
    crawl:print(Root)
  catch
    ErrorType:Error ->
      io:format("Error: ~s ~s~n", [ErrorType, Error])
    end;
main(_) ->
  usage().

usage() ->
  io:format("usage: crawl path\n"),
    halt(1).
